server:
  port: 8081
spring:
  devtools:
    restart:    #需要实时更新的目录
      additional-paths: resources/**,static/**,templates/**
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 47.114.36.156
    port: 6379
    password: redis123
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5
        max-wait: 30s
    timeout: 10s


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rbac?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat,wall,sl4j
    connectionProperties: druid.stat.mergeSql=true;
    druid:
      initial-size: 1
      minIdle: 3
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
mybatis:
  type-aliases-package: com.hf.friday.model
  mapper-locations: classpath:/mybatis-mappers/*
  configuration:
    mapUnderscoreToCamelCase: true
    cache-enabled: false
logging:
  path: E:/demolog
druid:
  stat:
    slowSqlMillis: 5000

api-url: /api
file:
  ###静态资源实际存储路径
  standardPath: E:/upload/
  ###缩略图保存路径
  thumbnailPath: E:/upload/thumbnail/
  ###静态资源对外暴露的访问路径
  staticAccessStandardPath: /file/**
  staticAccessThumbnailPath: /file/thumbnail/**

comic:
  path: E:/upload/comic/
  staticAccesspath: /comic/**